//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpswatwpscorelu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lkpswatwpscorelu()
        {
            this.tblswatwpscores = new HashSet<tblswatwpscore>();
        }
    
        public int ID { get; set; }
        public string ScoreName { get; set; }
        public string Description { get; set; }
        public Nullable<int> SectionID { get; set; }
    
        public virtual lkpswatwpsectionlu lkpswatwpsectionlu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpscore> tblswatwpscores { get; set; }
    }
}
