//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpswatwatermonthlu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lkpswatwatermonthlu()
        {
            this.tblswatwamonthlyquantities = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities1 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities2 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities3 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities4 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities5 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities6 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities7 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities8 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities9 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities10 = new HashSet<tblswatwamonthlyquantity>();
            this.tblswatwamonthlyquantities11 = new HashSet<tblswatwamonthlyquantity>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwamonthlyquantity> tblswatwamonthlyquantities11 { get; set; }
    }
}
