//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpswat5ranklu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lkpswat5ranklu()
        {
            this.tblswatccschools = new HashSet<tblswatccschool>();
            this.tblswatccsocials = new HashSet<tblswatccsocial>();
            this.tblswatccsocials1 = new HashSet<tblswatccsocial>();
            this.tblswatccwatermanagements = new HashSet<tblswatccwatermanagement>();
            this.tblswatccwatermanagements1 = new HashSet<tblswatccwatermanagement>();
            this.tblswatccwatermanagements2 = new HashSet<tblswatccwatermanagement>();
            this.tblswatccwatermanagements3 = new HashSet<tblswatccwatermanagement>();
            this.tblswatccwatermanagements4 = new HashSet<tblswatccwatermanagement>();
            this.tblswathppcoms = new HashSet<tblswathppcom>();
            this.tblswathppkhps = new HashSet<tblswathppkhp>();
            this.tblswatsfcentrals = new HashSet<tblswatsfcentral>();
            this.tblswatsfseptics = new HashSet<tblswatsfseptic>();
            this.tblswatsfseptics1 = new HashSet<tblswatsfseptic>();
            this.tblswatswpags = new HashSet<tblswatswpag>();
            this.tblswatswpags1 = new HashSet<tblswatswpag>();
            this.tblswatswpdevs = new HashSet<tblswatswpdev>();
            this.tblswatswpls = new HashSet<tblswatswpl>();
            this.tblswatwpsupplies = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies1 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies2 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies3 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies4 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies5 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies6 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies7 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies8 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies9 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies10 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies11 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies12 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies13 = new HashSet<tblswatwpsupply>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatccschool> tblswatccschools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatccsocial> tblswatccsocials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatccsocial> tblswatccsocials1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatccwatermanagement> tblswatccwatermanagements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatccwatermanagement> tblswatccwatermanagements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatccwatermanagement> tblswatccwatermanagements2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatccwatermanagement> tblswatccwatermanagements3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatccwatermanagement> tblswatccwatermanagements4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswathppcom> tblswathppcoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswathppkhp> tblswathppkhps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsfcentral> tblswatsfcentrals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsfseptic> tblswatsfseptics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsfseptic> tblswatsfseptics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatswpag> tblswatswpags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatswpag> tblswatswpags1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatswpdev> tblswatswpdevs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatswpl> tblswatswpls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies13 { get; set; }
    }
}
