//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpswatwpareliabilitymonthlu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lkpswatwpareliabilitymonthlu()
        {
            this.tblswatwpsupplies = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies1 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies2 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies3 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies4 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies5 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies6 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies7 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies8 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies9 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies10 = new HashSet<tblswatwpsupply>();
            this.tblswatwpsupplies11 = new HashSet<tblswatwpsupply>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies11 { get; set; }
    }
}
