//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpswatyesnolu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lkpswatyesnolu()
        {
            this.tblswatbackgroundinfoes = new HashSet<tblswatbackgroundinfo>();
            this.tblswatbackgroundinfoes1 = new HashSet<tblswatbackgroundinfo>();
            this.tblswatbackgroundinfoes2 = new HashSet<tblswatbackgroundinfo>();
            this.tblswatsfcentrals = new HashSet<tblswatsfcentral>();
            this.tblswatsfcentrals1 = new HashSet<tblswatsfcentral>();
            this.tblswatsfcentrals2 = new HashSet<tblswatsfcentral>();
            this.tblswatsflats = new HashSet<tblswatsflat>();
            this.tblswatsflats1 = new HashSet<tblswatsflat>();
            this.tblswatsflats2 = new HashSet<tblswatsflat>();
            this.tblswatsfseptics = new HashSet<tblswatsfseptic>();
            this.tblswatsfseptics1 = new HashSet<tblswatsfseptic>();
            this.tblswatsfseptics2 = new HashSet<tblswatsfseptic>();
            this.tblswatwagroundwaters = new HashSet<tblswatwagroundwater>();
            this.tblswatwpswprs = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs1 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs2 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs3 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs4 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs5 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs6 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs7 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs8 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs9 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs10 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs11 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs12 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs13 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs14 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs15 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs16 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs17 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs18 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs19 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs20 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs21 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs22 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs23 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs24 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs25 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs26 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs27 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs28 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs29 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs30 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs31 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs32 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs33 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs34 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs35 = new HashSet<tblswatwpswpr>();
            this.tblswatwpswprs36 = new HashSet<tblswatwpswpr>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatbackgroundinfo> tblswatbackgroundinfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatbackgroundinfo> tblswatbackgroundinfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatbackgroundinfo> tblswatbackgroundinfoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsfcentral> tblswatsfcentrals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsfcentral> tblswatsfcentrals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsfcentral> tblswatsfcentrals2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsflat> tblswatsflats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsflat> tblswatsflats1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsflat> tblswatsflats2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsfseptic> tblswatsfseptics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsfseptic> tblswatsfseptics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsfseptic> tblswatsfseptics2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwagroundwater> tblswatwagroundwaters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs34 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs35 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs36 { get; set; }
    }
}
