//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWATEntities : DbContext
    {
        public SWATEntities()
            : base("name=SWATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lkpbiome> lkpbiomes { get; set; }
        public virtual DbSet<lkpclimateclassification> lkpclimateclassifications { get; set; }
        public virtual DbSet<lkpcountry> lkpcountries { get; set; }
        public virtual DbSet<lkpcurrency> lkpcurrencies { get; set; }
        public virtual DbSet<lkpregion> lkpregions { get; set; }
        public virtual DbSet<lkpsoil> lkpsoils { get; set; }
        public virtual DbSet<lkpsubnational> lkpsubnationals { get; set; }
        public virtual DbSet<lkpswat5ranklu> lkpswat5ranklu { get; set; }
        public virtual DbSet<lkpswatareabmlu> lkpswatareabmlus { get; set; }
        public virtual DbSet<lkpswatareaprotlu> lkpswatareaprotlus { get; set; }
        public virtual DbSet<lkpswatbestmanagementlu> lkpswatbestmanagementlus { get; set; }
        public virtual DbSet<lkpswatbestmanindlu> lkpswatbestmanindlus { get; set; }
        public virtual DbSet<lkpswatcentralconditionlu> lkpswatcentralconditionlus { get; set; }
        public virtual DbSet<lkpswatcentraltreatmenttypelu> lkpswatcentraltreatmenttypelus { get; set; }
        public virtual DbSet<lkpswatcollectdangerlu> lkpswatcollectdangerlus { get; set; }
        public virtual DbSet<lkpswatcomponentlu> lkpswatcomponentlus { get; set; }
        public virtual DbSet<lkpswatcomsatisfactionlu> lkpswatcomsatisfactionlus { get; set; }
        public virtual DbSet<lkpswatcroplosslu> lkpswatcroplosslus { get; set; }
        public virtual DbSet<lkpswatdevsitelu> lkpswatdevsitelus { get; set; }
        public virtual DbSet<lkpswatdomwateruseslu> lkpswatdomwateruseslus { get; set; }
        public virtual DbSet<lkpswateaseuselu> lkpswateaseuselus { get; set; }
        public virtual DbSet<lkpswateconprislu> lkpswateconprislus { get; set; }
        public virtual DbSet<lkpswatedugraddifflu> lkpswatedugraddifflus { get; set; }
        public virtual DbSet<lkpswaterosionlu> lkpswaterosionlus { get; set; }
        public virtual DbSet<lkpswatextremeeventslu> lkpswatextremeeventslus { get; set; }
        public virtual DbSet<lkpswatextremepreplu> lkpswatextremepreplus { get; set; }
        public virtual DbSet<lkpswatextremerisklu> lkpswatextremerisklus { get; set; }
        public virtual DbSet<lkpswatextvisitlu> lkpswatextvisitlus { get; set; }
        public virtual DbSet<lkpswatfaecalpathogenslu> lkpswatfaecalpathogenslus { get; set; }
        public virtual DbSet<lkpswatfundapplu> lkpswatfundapplus { get; set; }
        public virtual DbSet<lkpswatfundappsuccesslu> lkpswatfundappsuccesslus { get; set; }
        public virtual DbSet<lkpswatgenderlu> lkpswatgenderlus { get; set; }
        public virtual DbSet<lkpswatgovrightslu> lkpswatgovrightslus { get; set; }
        public virtual DbSet<lkpswatgovwatanallu> lkpswatgovwatanallus { get; set; }
        public virtual DbSet<lkpswatgovwatpollu> lkpswatgovwatpollus { get; set; }
        public virtual DbSet<lkpswatgrolewomenlu> lkpswatgrolewomenlus { get; set; }
        public virtual DbSet<lkpswatgwavailabilitylu> lkpswatgwavailabilitylus { get; set; }
        public virtual DbSet<lkpswatgwomenengagedlu> lkpswatgwomenengagedlus { get; set; }
        public virtual DbSet<lkpswathhcleanlu> lkpswathhcleanlus { get; set; }
        public virtual DbSet<lkpswatindicatorgrouplu> lkpswatindicatorgrouplus { get; set; }
        public virtual DbSet<lkpswatindigpoplu> lkpswatindigpoplus { get; set; }
        public virtual DbSet<lkpswatlatrineconditionlu> lkpswatlatrineconditionlus { get; set; }
        public virtual DbSet<lkpswatlongtermpoplu> lkpswatlongtermpoplus { get; set; }
        public virtual DbSet<lkpswatmaparidity> lkpswatmaparidities { get; set; }
        public virtual DbSet<lkpswatmedicalcostlu> lkpswatmedicalcostlus { get; set; }
        public virtual DbSet<lkpswatmedicaltimelu> lkpswatmedicaltimelus { get; set; }
        public virtual DbSet<lkpswatpipedagelu> lkpswatpipedagelus { get; set; }
        public virtual DbSet<lkpswatpipedbalancelu> lkpswatpipedbalancelus { get; set; }
        public virtual DbSet<lkpswatpipedcost1lu> lkpswatpipedcost1lu { get; set; }
        public virtual DbSet<lkpswatpipedcost2lu> lkpswatpipedcost2lu { get; set; }
        public virtual DbSet<lkpswatpipedcost3lu> lkpswatpipedcost3lu { get; set; }
        public virtual DbSet<lkpswatpipedsuitabilitylu> lkpswatpipedsuitabilitylus { get; set; }
        public virtual DbSet<lkpswatpreciplu> lkpswatpreciplus { get; set; }
        public virtual DbSet<lkpswatprecipvaraltlu> lkpswatprecipvaraltlus { get; set; }
        public virtual DbSet<lkpswatprecipvardivmeanlu> lkpswatprecipvardivmeanlus { get; set; }
        public virtual DbSet<lkpswatpriorlu> lkpswatpriorlus { get; set; }
        public virtual DbSet<lkpswatpropoorlu> lkpswatpropoorlus { get; set; }
        public virtual DbSet<lkpswatpubcleanlu> lkpswatpubcleanlus { get; set; }
        public virtual DbSet<lkpswatqualtreatedlu> lkpswatqualtreatedlus { get; set; }
        public virtual DbSet<lkpswatroscalu> lkpswatroscalus { get; set; }
        public virtual DbSet<lkpswatrunofflu> lkpswatrunofflus { get; set; }
        public virtual DbSet<lkpswatsantypelu> lkpswatsantypelus { get; set; }
        public virtual DbSet<lkpswatscores_5rankalwaysbad> lkpswatscores_5rankalwaysbad { get; set; }
        public virtual DbSet<lkpswatscores_5rankalwaysgood> lkpswatscores_5rankalwaysgood { get; set; }
        public virtual DbSet<lkpswatscores_areabmlu> lkpswatscores_areabmlu { get; set; }
        public virtual DbSet<lkpswatscores_areaprot> lkpswatscores_areaprot { get; set; }
        public virtual DbSet<lkpswatscores_aridity> lkpswatscores_aridity { get; set; }
        public virtual DbSet<lkpswatscores_bestmanagement> lkpswatscores_bestmanagement { get; set; }
        public virtual DbSet<lkpswatscores_bestmanind> lkpswatscores_bestmanind { get; set; }
        public virtual DbSet<lkpswatscores_centralcondition> lkpswatscores_centralcondition { get; set; }
        public virtual DbSet<lkpswatscores_centraltreatment> lkpswatscores_centraltreatment { get; set; }
        public virtual DbSet<lkpswatscores_collectdanger> lkpswatscores_collectdanger { get; set; }
        public virtual DbSet<lkpswatscores_comsatisfaction> lkpswatscores_comsatisfaction { get; set; }
        public virtual DbSet<lkpswatscores_croploss> lkpswatscores_croploss { get; set; }
        public virtual DbSet<lkpswatscores_domwateruses> lkpswatscores_domwateruses { get; set; }
        public virtual DbSet<lkpswatscores_easeuse> lkpswatscores_easeuse { get; set; }
        public virtual DbSet<lkpswatscores_econpris> lkpswatscores_econpris { get; set; }
        public virtual DbSet<lkpswatscores_edugraddiff> lkpswatscores_edugraddiff { get; set; }
        public virtual DbSet<lkpswatscores_erosion> lkpswatscores_erosion { get; set; }
        public virtual DbSet<lkpswatscores_extremeevents> lkpswatscores_extremeevents { get; set; }
        public virtual DbSet<lkpswatscores_extremeprep> lkpswatscores_extremeprep { get; set; }
        public virtual DbSet<lkpswatscores_extremerisk> lkpswatscores_extremerisk { get; set; }
        public virtual DbSet<lkpswatscores_extvisit> lkpswatscores_extvisit { get; set; }
        public virtual DbSet<lkpswatscores_faecalpathogens> lkpswatscores_faecalpathogens { get; set; }
        public virtual DbSet<lkpswatscores_fundappfund> lkpswatscores_fundappfund { get; set; }
        public virtual DbSet<lkpswatscores_fundapplink> lkpswatscores_fundapplink { get; set; }
        public virtual DbSet<lkpswatscores_fundappsuccess> lkpswatscores_fundappsuccess { get; set; }
        public virtual DbSet<lkpswatscores_gender> lkpswatscores_gender { get; set; }
        public virtual DbSet<lkpswatscores_govrights> lkpswatscores_govrights { get; set; }
        public virtual DbSet<lkpswatscores_govwatanal> lkpswatscores_govwatanal { get; set; }
        public virtual DbSet<lkpswatscores_govwatpol> lkpswatscores_govwatpol { get; set; }
        public virtual DbSet<lkpswatscores_grolewomen> lkpswatscores_grolewomen { get; set; }
        public virtual DbSet<lkpswatscores_gwavailability> lkpswatscores_gwavailability { get; set; }
        public virtual DbSet<lkpswatscores_gwomenengaged> lkpswatscores_gwomenengaged { get; set; }
        public virtual DbSet<lkpswatscores_hhclean> lkpswatscores_hhclean { get; set; }
        public virtual DbSet<lkpswatscores_indigpop> lkpswatscores_indigpop { get; set; }
        public virtual DbSet<lkpswatscores_latrinecondition> lkpswatscores_latrinecondition { get; set; }
        public virtual DbSet<lkpswatscores_longtermpop> lkpswatscores_longtermpop { get; set; }
        public virtual DbSet<lkpswatscores_medicalcost> lkpswatscores_medicalcost { get; set; }
        public virtual DbSet<lkpswatscores_medicaltime> lkpswatscores_medicaltime { get; set; }
        public virtual DbSet<lkpswatscores_pipedage> lkpswatscores_pipedage { get; set; }
        public virtual DbSet<lkpswatscores_pipedbalance> lkpswatscores_pipedbalance { get; set; }
        public virtual DbSet<lkpswatscores_pipedcost1> lkpswatscores_pipedcost1 { get; set; }
        public virtual DbSet<lkpswatscores_pipedcost2> lkpswatscores_pipedcost2 { get; set; }
        public virtual DbSet<lkpswatscores_pipedcost3> lkpswatscores_pipedcost3 { get; set; }
        public virtual DbSet<lkpswatscores_pipedsuitability> lkpswatscores_pipedsuitability { get; set; }
        public virtual DbSet<lkpswatscores_precip> lkpswatscores_precip { get; set; }
        public virtual DbSet<lkpswatscores_precipvar> lkpswatscores_precipvar { get; set; }
        public virtual DbSet<lkpswatscores_propoor> lkpswatscores_propoor { get; set; }
        public virtual DbSet<lkpswatscores_pubclean> lkpswatscores_pubclean { get; set; }
        public virtual DbSet<lkpswatscores_qualtreated> lkpswatscores_qualtreated { get; set; }
        public virtual DbSet<lkpswatscores_rosca> lkpswatscores_rosca { get; set; }
        public virtual DbSet<lkpswatscores_runoff> lkpswatscores_runoff { get; set; }
        public virtual DbSet<lkpswatscores_santype> lkpswatscores_santype { get; set; }
        public virtual DbSet<lkpswatscores_soccbo> lkpswatscores_soccbo { get; set; }
        public virtual DbSet<lkpswatscores_surfacevar> lkpswatscores_surfacevar { get; set; }
        public virtual DbSet<lkpswatscores_survivorship> lkpswatscores_survivorship { get; set; }
        public virtual DbSet<lkpswatscores_toiletsall> lkpswatscores_toiletsall { get; set; }
        public virtual DbSet<lkpswatscores_urbandistance> lkpswatscores_urbandistance { get; set; }
        public virtual DbSet<lkpswatscores_usertreatediftreatedbefore> lkpswatscores_usertreatediftreatedbefore { get; set; }
        public virtual DbSet<lkpswatscores_usertreatedifuntreatedbefore> lkpswatscores_usertreatedifuntreatedbefore { get; set; }
        public virtual DbSet<lkpswatscores_usertreatmentmethod> lkpswatscores_usertreatmentmethod { get; set; }
        public virtual DbSet<lkpswatscores_watactionplan> lkpswatscores_watactionplan { get; set; }
        public virtual DbSet<lkpswatscores_watbudget> lkpswatscores_watbudget { get; set; }
        public virtual DbSet<lkpswatscores_watclassrep> lkpswatscores_watclassrep { get; set; }
        public virtual DbSet<lkpswatscores_watcom> lkpswatscores_watcom { get; set; }
        public virtual DbSet<lkpswatscores_watcomconcerns> lkpswatscores_watcomconcerns { get; set; }
        public virtual DbSet<lkpswatscores_watercollecttime> lkpswatscores_watercollecttime { get; set; }
        public virtual DbSet<lkpswatscores_watereffort> lkpswatscores_watereffort { get; set; }
        public virtual DbSet<lkpswatscores_watertasteodour> lkpswatscores_watertasteodour { get; set; }
        public virtual DbSet<lkpswatscores_waterturbidity> lkpswatscores_waterturbidity { get; set; }
        public virtual DbSet<lkpswatscores_wattechstaff> lkpswatscores_wattechstaff { get; set; }
        public virtual DbSet<lkpswatscores_wattechtraining> lkpswatscores_wattechtraining { get; set; }
        public virtual DbSet<lkpswatscores_wpareliabilitymonth> lkpswatscores_wpareliabilitymonth { get; set; }
        public virtual DbSet<lkpswatscores_yesnolu_yesbad> lkpswatscores_yesnolu_yesbad { get; set; }
        public virtual DbSet<lkpswatscores_yesnoluyesgood> lkpswatscores_yesnoluyesgood { get; set; }
        public virtual DbSet<lkpswatscorevarslu> lkpswatscorevarslus { get; set; }
        public virtual DbSet<lkpswatsectionlu> lkpswatsectionlus { get; set; }
        public virtual DbSet<lkpswatsoccbolu> lkpswatsoccbolus { get; set; }
        public virtual DbSet<lkpswatsubcomponentlu> lkpswatsubcomponentlus { get; set; }
        public virtual DbSet<lkpswatsurfacevarlu> lkpswatsurfacevarlus { get; set; }
        public virtual DbSet<lkpswatsurvivorshiplu> lkpswatsurvivorshiplus { get; set; }
        public virtual DbSet<lkpswattoiletsalllu> lkpswattoiletsalllus { get; set; }
        public virtual DbSet<lkpswaturbandistancelu> lkpswaturbandistancelus { get; set; }
        public virtual DbSet<lkpswatusertreatedlu> lkpswatusertreatedlus { get; set; }
        public virtual DbSet<lkpswatusertreatmentmethodlu> lkpswatusertreatmentmethodlus { get; set; }
        public virtual DbSet<lkpswatwaprecipitation> lkpswatwaprecipitations { get; set; }
        public virtual DbSet<lkpswatwatactionplanlu> lkpswatwatactionplanlus { get; set; }
        public virtual DbSet<lkpswatwatbudgetlu> lkpswatwatbudgetlus { get; set; }
        public virtual DbSet<lkpswatwatclassreplu> lkpswatwatclassreplus { get; set; }
        public virtual DbSet<lkpswatwatcomconcernslu> lkpswatwatcomconcernslus { get; set; }
        public virtual DbSet<lkpswatwatcomlu> lkpswatwatcomlus { get; set; }
        public virtual DbSet<lkpswatwatercollecttimelu> lkpswatwatercollecttimelus { get; set; }
        public virtual DbSet<lkpswatwatereffortlu> lkpswatwatereffortlus { get; set; }
        public virtual DbSet<lkpswatwatermonthlu> lkpswatwatermonthlus { get; set; }
        public virtual DbSet<lkpswatwatershedslu> lkpswatwatershedslus { get; set; }
        public virtual DbSet<lkpswatwatertasteodourlu> lkpswatwatertasteodourlus { get; set; }
        public virtual DbSet<lkpswatwaterturbiditylu> lkpswatwaterturbiditylus { get; set; }
        public virtual DbSet<lkpswatwattechstafflu> lkpswatwattechstafflus { get; set; }
        public virtual DbSet<lkpswatwattechtraininglu> lkpswatwattechtraininglus { get; set; }
        public virtual DbSet<lkpswatwpaloc> lkpswatwpalocs { get; set; }
        public virtual DbSet<lkpswatwpareliabilitymonthlu> lkpswatwpareliabilitymonthlus { get; set; }
        public virtual DbSet<lkpswatwpatypedesc> lkpswatwpatypedescs { get; set; }
        public virtual DbSet<lkpswatwpcomponentlu> lkpswatwpcomponentlus { get; set; }
        public virtual DbSet<lkpswatwpindicatorgrouplu> lkpswatwpindicatorgrouplus { get; set; }
        public virtual DbSet<lkpswatwpscorelu> lkpswatwpscorelus { get; set; }
        public virtual DbSet<lkpswatwpsectionlu> lkpswatwpsectionlus { get; set; }
        public virtual DbSet<lkpswatwpsubcomponentlu> lkpswatwpsubcomponentlus { get; set; }
        public virtual DbSet<lkpswatyesnolu> lkpswatyesnolus { get; set; }
        public virtual DbSet<tblresource> tblresources { get; set; }
        public virtual DbSet<tblswatbackgroundinfo> tblswatbackgroundinfoes { get; set; }
        public virtual DbSet<tblswatcccom> tblswatcccoms { get; set; }
        public virtual DbSet<tblswatccedu> tblswatccedus { get; set; }
        public virtual DbSet<tblswatccexternalsupport> tblswatccexternalsupports { get; set; }
        public virtual DbSet<tblswatccfinancial> tblswatccfinancials { get; set; }
        public virtual DbSet<tblswatccgender> tblswatccgenders { get; set; }
        public virtual DbSet<tblswatccindig> tblswatccindigs { get; set; }
        public virtual DbSet<tblswatccschool> tblswatccschools { get; set; }
        public virtual DbSet<tblswatccsocial> tblswatccsocials { get; set; }
        public virtual DbSet<tblswatcctrain> tblswatcctrains { get; set; }
        public virtual DbSet<tblswatccwatermanagement> tblswatccwatermanagements { get; set; }
        public virtual DbSet<tblswathppcom> tblswathppcoms { get; set; }
        public virtual DbSet<tblswathppkhp> tblswathppkhps { get; set; }
        public virtual DbSet<tblswatlocation> tblswatlocations { get; set; }
        public virtual DbSet<tblswatscore> tblswatscores { get; set; }
        public virtual DbSet<tblswatsfcentral> tblswatsfcentrals { get; set; }
        public virtual DbSet<tblswatsflat> tblswatsflats { get; set; }
        public virtual DbSet<tblswatsfod> tblswatsfods { get; set; }
        public virtual DbSet<tblswatsfpoint> tblswatsfpoints { get; set; }
        public virtual DbSet<tblswatsfsanitation> tblswatsfsanitations { get; set; }
        public virtual DbSet<tblswatsfseptic> tblswatsfseptics { get; set; }
        public virtual DbSet<tblswatsurvey> tblswatsurveys { get; set; }
        public virtual DbSet<tblswatswpag> tblswatswpags { get; set; }
        public virtual DbSet<tblswatswpdev> tblswatswpdevs { get; set; }
        public virtual DbSet<tblswatswpl> tblswatswpls { get; set; }
        public virtual DbSet<tblswatvisualgroup> tblswatvisualgroups { get; set; }
        public virtual DbSet<tblswatvisualgrpscoremap> tblswatvisualgrpscoremaps { get; set; }
        public virtual DbSet<tblswatwaannualprecip> tblswatwaannualprecips { get; set; }
        public virtual DbSet<tblswatwaclimatechange> tblswatwaclimatechanges { get; set; }
        public virtual DbSet<tblswatwaextremeevent> tblswatwaextremeevents { get; set; }
        public virtual DbSet<tblswatwagroundwater> tblswatwagroundwaters { get; set; }
        public virtual DbSet<tblswatwamonthlyquantity> tblswatwamonthlyquantities { get; set; }
        public virtual DbSet<tblswatwaprecipitation> tblswatwaprecipitations { get; set; }
        public virtual DbSet<tblswatwariskprep> tblswatwariskpreps { get; set; }
        public virtual DbSet<tblswatwasurfacewater> tblswatwasurfacewaters { get; set; }
        public virtual DbSet<tblswatwpoverview> tblswatwpoverviews { get; set; }
        public virtual DbSet<tblswatwpquality> tblswatwpqualities { get; set; }
        public virtual DbSet<tblswatwpscore> tblswatwpscores { get; set; }
        public virtual DbSet<tblswatwpsupply> tblswatwpsupplies { get; set; }
        public virtual DbSet<tblswatwpswpr> tblswatwpswprs { get; set; }
        public virtual DbSet<userid> userids { get; set; }
        public virtual DbSet<lkpswatindicatorsubcomponentlu> lkpswatindicatorsubcomponentlus { get; set; }
        public virtual DbSet<lkpswatscorevarsectionlu> lkpswatscorevarsectionlus { get; set; }
        public virtual DbSet<lkpswatwpscorecomponentlu> lkpswatwpscorecomponentlus { get; set; }
        public virtual DbSet<lkpswatwpscoresubcomponentlu> lkpswatwpscoresubcomponentlus { get; set; }
    }
}
