//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatwariskprep
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> riskFire { get; set; }
        public Nullable<int> riskFlood { get; set; }
        public Nullable<int> riskDrought { get; set; }
        public Nullable<int> prepFire { get; set; }
        public Nullable<int> prepFlood { get; set; }
        public Nullable<int> prepDrought { get; set; }
    
        public virtual lkpswatextremepreplu lkpswatextremepreplu { get; set; }
        public virtual lkpswatextremepreplu lkpswatextremepreplu1 { get; set; }
        public virtual lkpswatextremepreplu lkpswatextremepreplu2 { get; set; }
        public virtual lkpswatextremerisklu lkpswatextremerisklu { get; set; }
        public virtual lkpswatextremerisklu lkpswatextremerisklu1 { get; set; }
        public virtual lkpswatextremerisklu lkpswatextremerisklu2 { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
