//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatwpsupply
    {
        public long ID { get; set; }
        public long wpID { get; set; }
        public Nullable<int> conflictWater { get; set; }
        public Nullable<float> domPercentUse { get; set; }
        public Nullable<int> domCollectDry1 { get; set; }
        public Nullable<float> domCollectDryAmount1 { get; set; }
        public Nullable<int> domCollectWet1 { get; set; }
        public Nullable<float> domCollectWetAmount1 { get; set; }
        public Nullable<int> domCollectDry2 { get; set; }
        public Nullable<float> domCollectDryAmount2 { get; set; }
        public Nullable<int> domCollectWet2 { get; set; }
        public Nullable<float> domCollectWetAmount2 { get; set; }
        public Nullable<int> domCollectDry3 { get; set; }
        public Nullable<float> domCollectDryAmount3 { get; set; }
        public Nullable<int> domCollectWet3 { get; set; }
        public Nullable<float> domCollectWetAmount3 { get; set; }
        public Nullable<int> domPipedNumHHDry { get; set; }
        public Nullable<int> domPipedNumHHWet { get; set; }
        public Nullable<int> domWaterUses { get; set; }
        public Nullable<int> domwaterCollectTime { get; set; }
        public Nullable<int> domwaterEffort { get; set; }
        public Nullable<int> domcollectDanger { get; set; }
        public bool domdangerType1 { get; set; }
        public bool domdangerType2 { get; set; }
        public bool domdangerType3 { get; set; }
        public Nullable<int> domdemoWaterFetch1 { get; set; }
        public Nullable<int> domdemoWaterFetch2 { get; set; }
        public Nullable<int> domdemoWaterFetch3 { get; set; }
        public Nullable<int> domdemoWaterFetch4 { get; set; }
        public Nullable<int> domdemoWaterFetch5 { get; set; }
        public bool wpaInstitutionHigh1 { get; set; }
        public bool wpaInstitutionHigh2 { get; set; }
        public bool wpaInstitutionHigh3 { get; set; }
        public bool wpaInstitutionHigh4 { get; set; }
        public bool wpaInstitutionLow1 { get; set; }
        public bool wpaInstitutionLow2 { get; set; }
        public bool wpaInstitutionLow3 { get; set; }
        public bool wpaInstitutionLow4 { get; set; }
        public Nullable<int> wpaInstitutionPeopleServedWet { get; set; }
        public Nullable<int> wpaInstitutionPeopleServedDry { get; set; }
        public Nullable<int> wpaInstitutionSupply { get; set; }
        public Nullable<int> inwaterCollectTime { get; set; }
        public Nullable<int> inwaterEffort { get; set; }
        public Nullable<int> incollectDanger { get; set; }
        public bool indangerType1 { get; set; }
        public bool indangerType2 { get; set; }
        public bool indangerType3 { get; set; }
        public Nullable<int> indemoWaterFetch1 { get; set; }
        public Nullable<int> indemoWaterFetch2 { get; set; }
        public Nullable<int> indemoWaterFetch3 { get; set; }
        public Nullable<int> indemoWaterFetch4 { get; set; }
        public Nullable<int> indemoWaterFetch5 { get; set; }
        public bool ecWaterUse1 { get; set; }
        public bool ecWaterUse2 { get; set; }
        public bool ecWaterUse3 { get; set; }
        public bool ecWaterUse4 { get; set; }
        public bool ecWaterUse5 { get; set; }
        public Nullable<float> ecWaterDemandDry { get; set; }
        public Nullable<float> ecWaterDemandWet { get; set; }
        public Nullable<int> ecSupply { get; set; }
        public Nullable<int> wpaInterruptionFreq { get; set; }
        public bool wpaInterruption1 { get; set; }
        public bool wpaInterruption2 { get; set; }
        public bool wpaInterruption3 { get; set; }
        public bool wpaInterruption4 { get; set; }
        public bool wpaInterruption5 { get; set; }
        public bool wpaInterruption6 { get; set; }
        public Nullable<int> wpaReliabilityMonth1 { get; set; }
        public Nullable<int> wpaReliabilityMonth2 { get; set; }
        public Nullable<int> wpaReliabilityMonth3 { get; set; }
        public Nullable<int> wpaReliabilityMonth4 { get; set; }
        public Nullable<int> wpaReliabilityMonth5 { get; set; }
        public Nullable<int> wpaReliabilityMonth6 { get; set; }
        public Nullable<int> wpaReliabilityMonth7 { get; set; }
        public Nullable<int> wpaReliabilityMonth8 { get; set; }
        public Nullable<int> wpaReliabilityMonth9 { get; set; }
        public Nullable<int> wpaReliabilityMonth10 { get; set; }
        public Nullable<int> wpaReliabilityMonth11 { get; set; }
        public Nullable<int> wpaReliabilityMonth12 { get; set; }
        public bool wpaReliabilityProblem1 { get; set; }
        public bool wpaReliabilityProblem2 { get; set; }
        public bool wpaReliabilityProblem3 { get; set; }
        public bool wpaReliabilityProblem4 { get; set; }
        public bool wpaReliabilityProblem5 { get; set; }
        public bool wpaReliabilityProblem6 { get; set; }
    
        public virtual lkpswat5ranklu lkpswat5ranklu { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu1 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu2 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu3 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu4 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu5 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu6 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu7 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu8 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu9 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu10 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu11 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu12 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu13 { get; set; }
        public virtual lkpswatcollectdangerlu lkpswatcollectdangerlu { get; set; }
        public virtual lkpswatcollectdangerlu lkpswatcollectdangerlu1 { get; set; }
        public virtual lkpswatdomwateruseslu lkpswatdomwateruseslu { get; set; }
        public virtual lkpswatwatercollecttimelu lkpswatwatercollecttimelu { get; set; }
        public virtual lkpswatwatercollecttimelu lkpswatwatercollecttimelu1 { get; set; }
        public virtual lkpswatwatereffortlu lkpswatwatereffortlu { get; set; }
        public virtual lkpswatwatereffortlu lkpswatwatereffortlu1 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu1 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu2 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu3 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu4 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu5 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu6 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu7 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu8 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu9 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu10 { get; set; }
        public virtual lkpswatwpareliabilitymonthlu lkpswatwpareliabilitymonthlu11 { get; set; }
        public virtual tblswatwpoverview tblswatwpoverview { get; set; }
    }
}
