//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatsfod
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public bool ODdemographic1 { get; set; }
        public bool ODdemographic2 { get; set; }
        public bool ODdemographic3 { get; set; }
        public bool ODdemographic4 { get; set; }
        public bool ODdemographicNONE { get; set; }
        public Nullable<int> hhNoToilet { get; set; }
        public Nullable<float> sharedFacPercent { get; set; }
        public Nullable<float> ODPercent { get; set; }
        public bool ODdemoGender1 { get; set; }
        public bool ODdemoGender2 { get; set; }
        public bool ODdemoGender3 { get; set; }
        public bool ODdemoGender4 { get; set; }
        public bool ODdemoGenderNONE { get; set; }
        public bool ODfacilitator1 { get; set; }
        public bool ODfacilitator2 { get; set; }
        public bool ODfacilitator3 { get; set; }
        public bool ODfacilitator4 { get; set; }
        public bool ODfacilitator5 { get; set; }
        public bool ODfacilitator6 { get; set; }
        public bool ODfacilitator7 { get; set; }
        public bool ODfacilitator8 { get; set; }
        public bool ODfacilitator9 { get; set; }
        public bool ODfacilitator10 { get; set; }
        public bool ODfacilitator11 { get; set; }
    
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
