//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatscore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblswatscore()
        {
            this.tblswatvisualgrpscoremaps = new HashSet<tblswatvisualgrpscoremap>();
        }
    
        public long ID { get; set; }
        public int SurveyID { get; set; }
        public int VariableID { get; set; }
        public Nullable<double> Value { get; set; }
        public string VarName { get; set; }
        public string Description { get; set; }
    
        public virtual lkpswatscorevarslu lkpswatscorevarslu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatvisualgrpscoremap> tblswatvisualgrpscoremaps { get; set; }
    }
}
