//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatwpswpr
    {
        public long ID { get; set; }
        public long wpID { get; set; }
        public Nullable<int> surfaceFenced { get; set; }
        public Nullable<int> surfaceUphill { get; set; }
        public Nullable<int> surfaceHealth { get; set; }
        public Nullable<int> springBox { get; set; }
        public Nullable<int> springBackfill { get; set; }
        public Nullable<int> springCover { get; set; }
        public Nullable<int> springWaterPool { get; set; }
        public Nullable<int> springAnimals { get; set; }
        public Nullable<int> springLatrine { get; set; }
        public Nullable<int> springUphill { get; set; }
        public Nullable<int> springDiversion { get; set; }
        public Nullable<int> boreholeLatrine { get; set; }
        public Nullable<int> boreholeUphill { get; set; }
        public Nullable<int> boreholeWellNear { get; set; }
        public Nullable<int> boreholeAnimals { get; set; }
        public Nullable<int> boreholePlatform { get; set; }
        public Nullable<int> boreholeSeal { get; set; }
        public Nullable<int> wellLatrine { get; set; }
        public Nullable<int> wellUphill { get; set; }
        public Nullable<int> wellAnimals { get; set; }
        public Nullable<int> wellPlatform { get; set; }
        public Nullable<int> wellCover { get; set; }
        public Nullable<int> rwFirstFlush { get; set; }
        public Nullable<int> rwOpen { get; set; }
        public Nullable<int> rwRoof { get; set; }
        public Nullable<int> rwGutters { get; set; }
        public Nullable<int> rwCracked { get; set; }
        public Nullable<int> rwDipper { get; set; }
        public Nullable<int> rwLeak { get; set; }
        public Nullable<int> rwDirty { get; set; }
        public Nullable<int> pipedStore { get; set; }
        public Nullable<int> pipedLeak { get; set; }
        public Nullable<int> pipedShare { get; set; }
        public Nullable<int> pipedAnimals { get; set; }
        public Nullable<int> pipedBreak { get; set; }
        public Nullable<int> pipedIllegal { get; set; }
        public Nullable<int> pipedSuitability { get; set; }
        public Nullable<int> pipedCosts1 { get; set; }
        public Nullable<int> pipedCosts2 { get; set; }
        public Nullable<int> pipedCosts3 { get; set; }
        public Nullable<float> pipedRevenue { get; set; }
        public Nullable<float> pipedExpenditure { get; set; }
        public Nullable<double> pipedBalance { get; set; }
        public Nullable<int> pipedCapital { get; set; }
        public Nullable<int> pipedAge { get; set; }
        public bool pipedFuture1 { get; set; }
        public bool pipedFuture2 { get; set; }
        public bool pipedFuture3 { get; set; }
        public bool pipedFuturePop1 { get; set; }
        public bool pipedFuturePop2 { get; set; }
        public bool pipedFuturePop3 { get; set; }
    
        public virtual lkpswatpipedagelu lkpswatpipedagelu { get; set; }
        public virtual lkpswatpipedcost1lu lkpswatpipedcost1lu { get; set; }
        public virtual lkpswatpipedcost2lu lkpswatpipedcost2lu { get; set; }
        public virtual lkpswatpipedcost3lu lkpswatpipedcost3lu { get; set; }
        public virtual lkpswatpipedsuitabilitylu lkpswatpipedsuitabilitylu { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu1 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu2 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu3 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu4 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu5 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu6 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu7 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu8 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu9 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu10 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu11 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu12 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu13 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu14 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu15 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu16 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu17 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu18 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu19 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu20 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu21 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu22 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu23 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu24 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu25 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu26 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu27 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu28 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu29 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu30 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu31 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu32 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu33 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu34 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu35 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu36 { get; set; }
        public virtual tblswatwpoverview tblswatwpoverview { get; set; }
    }
}
