//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatsfseptic
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> septicToilets { get; set; }
        public Nullable<float> septicUnderstand { get; set; }
        public Nullable<float> septicDistance { get; set; }
        public Nullable<float> septicPlug { get; set; }
        public Nullable<float> septicPumped { get; set; }
        public Nullable<float> septicTrash { get; set; }
        public Nullable<float> septicChemicals { get; set; }
        public Nullable<int> septicChemAvail { get; set; }
        public Nullable<int> septicPumpAvail { get; set; }
        public Nullable<int> septicPubClean { get; set; }
        public bool septicPubAccessGroup1 { get; set; }
        public bool septicPubAccessGroup2 { get; set; }
        public bool septicPubAccessGroup3 { get; set; }
        public Nullable<int> septicfeesCharged { get; set; }
        public Nullable<int> septicFeesLimitAccess { get; set; }
        public Nullable<int> septicFeesEnsureClean { get; set; }
        public Nullable<int> hhSepticClean { get; set; }
    
        public virtual lkpswat5ranklu lkpswat5ranklu { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu1 { get; set; }
        public virtual lkpswathhcleanlu lkpswathhcleanlu { get; set; }
        public virtual lkpswatpubcleanlu lkpswatpubcleanlu { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu1 { get; set; }
        public virtual lkpswatyesnolu lkpswatyesnolu2 { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
