//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatwpquality
    {
        public long ID { get; set; }
        public long wpID { get; set; }
        public Nullable<int> qualTreated { get; set; }
        public Nullable<int> userTreated { get; set; }
        public Nullable<int> userTreatmentMethod { get; set; }
        public Nullable<int> faecalPathogens { get; set; }
        public Nullable<int> waterTaste { get; set; }
        public Nullable<int> waterOdour { get; set; }
        public Nullable<int> waterTurbidity { get; set; }
    
        public virtual lkpswatfaecalpathogenslu lkpswatfaecalpathogenslu { get; set; }
        public virtual lkpswatqualtreatedlu lkpswatqualtreatedlu { get; set; }
        public virtual lkpswatusertreatedlu lkpswatusertreatedlu { get; set; }
        public virtual lkpswatusertreatmentmethodlu lkpswatusertreatmentmethodlu { get; set; }
        public virtual lkpswatwatertasteodourlu lkpswatwatertasteodourlu { get; set; }
        public virtual lkpswatwatertasteodourlu lkpswatwatertasteodourlu1 { get; set; }
        public virtual lkpswatwaterturbiditylu lkpswatwaterturbiditylu { get; set; }
        public virtual tblswatwpoverview tblswatwpoverview { get; set; }
    }
}
