//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatwaprecipitation
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<float> January { get; set; }
        public Nullable<float> February { get; set; }
        public Nullable<float> March { get; set; }
        public Nullable<float> April { get; set; }
        public Nullable<float> May { get; set; }
        public Nullable<float> June { get; set; }
        public Nullable<float> July { get; set; }
        public Nullable<float> August { get; set; }
        public Nullable<float> September { get; set; }
        public Nullable<float> October { get; set; }
        public Nullable<float> November { get; set; }
        public Nullable<float> December { get; set; }
        public Nullable<int> hasData { get; set; }
    
        public virtual lkpswatwaprecipitation lkpswatwaprecipitation { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
