//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswathppkhp
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<float> knowledgeQual { get; set; }
        public Nullable<float> trainingAccess1 { get; set; }
        public Nullable<float> trainingAccess2 { get; set; }
        public Nullable<float> trainingAccess3 { get; set; }
        public Nullable<float> trainingAccess4 { get; set; }
        public Nullable<float> trainingAccess5 { get; set; }
        public Nullable<int> promotion { get; set; }
        public Nullable<float> handWash { get; set; }
        public Nullable<float> childFaeces1 { get; set; }
        public Nullable<float> childFaeces2 { get; set; }
        public Nullable<float> childFaeces3 { get; set; }
        public Nullable<float> childFaeces4 { get; set; }
        public Nullable<float> childFaeces5 { get; set; }
        public Nullable<float> childFaeces6 { get; set; }
        public Nullable<float> childFaeces7 { get; set; }
    
        public virtual lkpswat5ranklu lkpswat5ranklu { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
