//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatccsocial
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> socHelp { get; set; }
        public Nullable<int> socClique { get; set; }
        public Nullable<int> socCBO { get; set; }
        public Nullable<float> socAttend { get; set; }
    
        public virtual lkpswat5ranklu lkpswat5ranklu { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu1 { get; set; }
        public virtual lkpswatsoccbolu lkpswatsoccbolu { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
