//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatccedu
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<float> eduPrim { get; set; }
        public Nullable<float> eduSec { get; set; }
        public Nullable<float> eduGradWomen { get; set; }
        public Nullable<float> eduGradMen { get; set; }
    
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
