//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatccfinancial
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<float> income { get; set; }
        public Nullable<int> rosca { get; set; }
        public bool assetsCom1 { get; set; }
        public bool assetsCom2 { get; set; }
        public bool assetsCom3 { get; set; }
        public bool assetsCom4 { get; set; }
        public bool assetsInd1 { get; set; }
        public bool assetsInd2 { get; set; }
        public bool assetsInd3 { get; set; }
        public bool assetsInd4 { get; set; }
    
        public virtual lkpswatroscalu lkpswatroscalu { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
