//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswathppcom
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> diarrhea { get; set; }
        public Nullable<int> survivorship { get; set; }
        public Nullable<int> medicalTime { get; set; }
        public Nullable<int> medicalCost { get; set; }
    
        public virtual lkpswat5ranklu lkpswat5ranklu { get; set; }
        public virtual lkpswatmedicalcostlu lkpswatmedicalcostlu { get; set; }
        public virtual lkpswatmedicaltimelu lkpswatmedicaltimelu { get; set; }
        public virtual lkpswatsurvivorshiplu lkpswatsurvivorshiplu { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
