//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatcccom
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public bool comResource1 { get; set; }
        public bool comResource2 { get; set; }
        public bool comResource3 { get; set; }
        public bool comResource4 { get; set; }
        public bool comResource5 { get; set; }
    
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
