//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatccwatermanagement
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> watCom { get; set; }
        public string watAdminOther { get; set; }
        public Nullable<int> watActionPlan { get; set; }
        public Nullable<int> watRecords1 { get; set; }
        public Nullable<int> watRecords2 { get; set; }
        public Nullable<int> watRecords3 { get; set; }
        public Nullable<int> watRecords4 { get; set; }
        public Nullable<int> watRecords5 { get; set; }
        public Nullable<int> comSatisfaction { get; set; }
        public Nullable<int> watClassRep { get; set; }
        public Nullable<int> watComConcerns { get; set; }
        public Nullable<int> watTechStaff { get; set; }
        public Nullable<int> watTechTraining { get; set; }
        public Nullable<int> watBudget { get; set; }
        public bool watFinPlan1 { get; set; }
        public bool watFinPlan2 { get; set; }
        public Nullable<int> proPoor { get; set; }
    
        public virtual lkpswat5ranklu lkpswat5ranklu { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu1 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu2 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu3 { get; set; }
        public virtual lkpswat5ranklu lkpswat5ranklu4 { get; set; }
        public virtual lkpswatcomsatisfactionlu lkpswatcomsatisfactionlu { get; set; }
        public virtual lkpswatpropoorlu lkpswatpropoorlu { get; set; }
        public virtual lkpswatwatactionplanlu lkpswatwatactionplanlu { get; set; }
        public virtual lkpswatwatbudgetlu lkpswatwatbudgetlu { get; set; }
        public virtual lkpswatwatclassreplu lkpswatwatclassreplu { get; set; }
        public virtual lkpswatwatcomconcernslu lkpswatwatcomconcernslu { get; set; }
        public virtual lkpswatwatcomlu lkpswatwatcomlu { get; set; }
        public virtual lkpswatwattechstafflu lkpswatwattechstafflu { get; set; }
        public virtual lkpswatwattechtraininglu lkpswatwattechtraininglu { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
