//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatswpl
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public bool livestock1 { get; set; }
        public bool livestock2 { get; set; }
        public Nullable<float> waterFenced { get; set; }
        public Nullable<int> livestockEffluent { get; set; }
    
        public virtual lkpswat5ranklu lkpswat5ranklu { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
