//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatwpoverview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblswatwpoverview()
        {
            this.tblswatwpqualities = new HashSet<tblswatwpquality>();
            this.tblswatwpscores = new HashSet<tblswatwpscore>();
            this.tblswatwpsupplies = new HashSet<tblswatwpsupply>();
            this.tblswatwpswprs = new HashSet<tblswatwpswpr>();
        }
    
        public long ID { get; set; }
        public int SurveyID { get; set; }
        public string wpname { get; set; }
        public Nullable<int> wpaLoc { get; set; }
        public bool wpaUseDom { get; set; }
        public bool wpaUseInst { get; set; }
        public bool wpaUseEc { get; set; }
        public string wpaType { get; set; }
    
        public virtual lkpswatwpaloc lkpswatwpaloc { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpquality> tblswatwpqualities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpscore> tblswatwpscores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpsupply> tblswatwpsupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatwpswpr> tblswatwpswprs { get; set; }
    }
}
