//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatwamonthlyquantity
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> January { get; set; }
        public Nullable<int> February { get; set; }
        public Nullable<int> March { get; set; }
        public Nullable<int> April { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> June { get; set; }
        public Nullable<int> July { get; set; }
        public Nullable<int> August { get; set; }
        public Nullable<int> September { get; set; }
        public Nullable<int> October { get; set; }
        public Nullable<int> November { get; set; }
        public Nullable<int> December { get; set; }
    
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu1 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu2 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu3 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu4 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu5 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu6 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu7 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu8 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu9 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu10 { get; set; }
        public virtual lkpswatwatermonthlu lkpswatwatermonthlu11 { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
