//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatwaextremeevent
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> extremeDry { get; set; }
        public Nullable<int> extremeFlood { get; set; }
        public Nullable<int> extremeOther { get; set; }
        public string extremeOtherComment { get; set; }
    
        public virtual lkpswatextremeeventslu lkpswatextremeeventslu { get; set; }
        public virtual lkpswatextremeeventslu lkpswatextremeeventslu1 { get; set; }
        public virtual lkpswatextremeeventslu lkpswatextremeeventslu2 { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
