//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatwaclimatechange
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public bool climateDryer { get; set; }
        public bool climateWetter { get; set; }
        public bool climateColder { get; set; }
        public bool climateHotter { get; set; }
        public bool climateSeasons { get; set; }
    
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
