//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatsfsanitation
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> toiletsAll { get; set; }
        public Nullable<float> toiletHome { get; set; }
        public Nullable<float> toiletYard { get; set; }
        public Nullable<float> toilet100 { get; set; }
        public Nullable<float> toilet500 { get; set; }
        public Nullable<float> toiletFar { get; set; }
    
        public virtual lkpswattoiletsalllu lkpswattoiletsalllu { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
