//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatlocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblswatlocation()
        {
            this.tblswatsurveys = new HashSet<tblswatsurvey>();
        }
    
        public int ID { get; set; }
        public float latitude { get; set; }
        public float longitude { get; set; }
        public int countryID { get; set; }
        public string name { get; set; }
        public int regionID { get; set; }
        public int subnationalID { get; set; }
    
        public virtual lkpcountry lkpcountry { get; set; }
        public virtual lkpregion lkpregion { get; set; }
        public virtual lkpsubnational lkpsubnational { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblswatsurvey> tblswatsurveys { get; set; }
    }
}
