//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblswatswpdev
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> devSite1 { get; set; }
        public Nullable<int> devSite2 { get; set; }
        public Nullable<int> devSite3 { get; set; }
        public Nullable<int> devSite4 { get; set; }
        public Nullable<int> devSiteTOTAL { get; set; }
        public Nullable<int> bestManInd { get; set; }
        public Nullable<int> wwTreatInd { get; set; }
    
        public virtual lkpswat5ranklu lkpswat5ranklu { get; set; }
        public virtual lkpswatbestmanindlu lkpswatbestmanindlu { get; set; }
        public virtual tblswatsurvey tblswatsurvey { get; set; }
    }
}
